#!/bin/bash
###############################################################################
# Bootstrap Terraform Backend
#
# This script creates the S3 bucket and DynamoDB table required for
# Terraform state storage and locking.
#
# Usage:
#   ./bootstrap-backend.sh [bucket-name] [table-name] [region]
#
# Example:
#   ./bootstrap-backend.sh portfolio-tf-state portfolio-tf-locks us-west-2
###############################################################################

set -euo pipefail

# Configuration
BUCKET_NAME="${1:-portfolio-tf-state}"
TABLE_NAME="${2:-portfolio-tf-locks}"
REGION="${3:-us-west-2}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Terraform Backend Bootstrap ===${NC}"
echo ""
echo "Configuration:"
echo "  Bucket: ${BUCKET_NAME}"
echo "  Table:  ${TABLE_NAME}"
echo "  Region: ${REGION}"
echo ""

# Check AWS CLI is available
if ! command -v aws &> /dev/null; then
    echo -e "${RED}Error: AWS CLI is not installed${NC}"
    exit 1
fi

# Check AWS credentials
echo -e "${YELLOW}Checking AWS credentials...${NC}"
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}Error: AWS credentials not configured${NC}"
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo -e "  Account: ${GREEN}${ACCOUNT_ID}${NC}"
echo ""

# Create S3 bucket
echo -e "${YELLOW}Creating S3 bucket...${NC}"
if aws s3api head-bucket --bucket "${BUCKET_NAME}" 2>/dev/null; then
    echo -e "  Bucket ${GREEN}${BUCKET_NAME}${NC} already exists"
else
    if [ "${REGION}" = "us-east-1" ]; then
        aws s3api create-bucket \
            --bucket "${BUCKET_NAME}" \
            --region "${REGION}"
    else
        aws s3api create-bucket \
            --bucket "${BUCKET_NAME}" \
            --region "${REGION}" \
            --create-bucket-configuration LocationConstraint="${REGION}"
    fi
    echo -e "  Bucket ${GREEN}${BUCKET_NAME}${NC} created"
fi

# Enable versioning
echo -e "${YELLOW}Enabling versioning...${NC}"
aws s3api put-bucket-versioning \
    --bucket "${BUCKET_NAME}" \
    --versioning-configuration Status=Enabled
echo -e "  Versioning ${GREEN}enabled${NC}"

# Enable server-side encryption
echo -e "${YELLOW}Enabling encryption...${NC}"
aws s3api put-bucket-encryption \
    --bucket "${BUCKET_NAME}" \
    --server-side-encryption-configuration '{
        "Rules": [{
            "ApplyServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
            },
            "BucketKeyEnabled": true
        }]
    }'
echo -e "  Encryption ${GREEN}enabled${NC}"

# Block public access
echo -e "${YELLOW}Blocking public access...${NC}"
aws s3api put-public-access-block \
    --bucket "${BUCKET_NAME}" \
    --public-access-block-configuration '{
        "BlockPublicAcls": true,
        "IgnorePublicAcls": true,
        "BlockPublicPolicy": true,
        "RestrictPublicBuckets": true
    }'
echo -e "  Public access ${GREEN}blocked${NC}"

echo ""

# Create DynamoDB table
echo -e "${YELLOW}Creating DynamoDB table...${NC}"
if aws dynamodb describe-table --table-name "${TABLE_NAME}" --region "${REGION}" 2>/dev/null; then
    echo -e "  Table ${GREEN}${TABLE_NAME}${NC} already exists"
else
    aws dynamodb create-table \
        --table-name "${TABLE_NAME}" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "${REGION}" \
        --tags Key=Name,Value="Terraform State Locks" Key=Project,Value=portfolio Key=ManagedBy,Value=terraform

    echo -e "  Table ${GREEN}${TABLE_NAME}${NC} created"

    # Wait for table to be active
    echo -e "${YELLOW}Waiting for table to be active...${NC}"
    aws dynamodb wait table-exists --table-name "${TABLE_NAME}" --region "${REGION}"
    echo -e "  Table ${GREEN}active${NC}"
fi

echo ""

# Generate backend.hcl
echo -e "${YELLOW}Generating backend.hcl...${NC}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_FILE="${SCRIPT_DIR}/../backend.hcl"

cat > "${BACKEND_FILE}" << EOF
# Terraform Backend Configuration
# Generated by bootstrap-backend.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Account: ${ACCOUNT_ID}

bucket         = "${BUCKET_NAME}"
key            = "project-1/terraform.tfstate"
region         = "${REGION}"
dynamodb_table = "${TABLE_NAME}"
encrypt        = true
EOF

echo -e "  backend.hcl ${GREEN}generated${NC}"

echo ""
echo -e "${GREEN}=== Bootstrap Complete ===${NC}"
echo ""
echo "Next steps:"
echo "  1. Initialize Terraform with the new backend:"
echo "     cd terraform && terraform init -backend-config=backend.hcl"
echo ""
echo "  2. If migrating existing state, use:"
echo "     terraform init -migrate-state -backend-config=backend.hcl"
echo ""
echo "  3. Verify the backend configuration:"
echo "     terraform state list"
echo ""
