from .base import BaseAnalyzer


class AndroidAnalyzer(BaseAnalyzer):
    platform = "android"

    def rules(self) -> list[dict]:
        return [
            {
                "pattern": r"Log\.(d|v|e|w|i)\s*\([^)]*(?:password|token|secret|key|auth|credential)[^)]*\)",
                "title": "Sensitive Data Leaked via Android Log",
                "description": "Sensitive data such as passwords, tokens, or credentials is being logged using Android's Log API. Log output is accessible to any app with READ_LOGS permission and is visible in ADB logcat, exposing credentials to attackers.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Remove all logging of sensitive data. Use ProGuard/R8 rules to strip log calls in release builds. Never log passwords, tokens, or PII.",
                "cwe_id": "CWE-532",
                "cvss_score": 7.5,
            },
            {
                "pattern": r"getSharedPreferences|SharedPreferences",
                "title": "Insecure Data Storage in SharedPreferences",
                "description": "SharedPreferences stores data in plaintext XML files on the device filesystem. Any data stored here — including tokens, session IDs, or preferences — is accessible to root users and through backup extraction on unencrypted devices.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Use Android Keystore for cryptographic keys. Use EncryptedSharedPreferences (Jetpack Security) for sensitive values. Never store plaintext passwords or tokens in SharedPreferences.",
                "cwe_id": "CWE-312",
                "cvss_score": 7.1,
            },
            {
                "pattern": r"setJavaScriptEnabled\s*\(\s*true\s*\)",
                "title": "WebView JavaScript Enabled — Potential XSS / RCE",
                "description": "Enabling JavaScript in a WebView without strict content validation opens the app to Cross-Site Scripting (XSS) attacks. If addJavascriptInterface() is also used, attackers can call Java methods via JavaScript, potentially achieving Remote Code Execution.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Disable JavaScript unless strictly necessary. If needed, use WebViewClient.shouldOverrideUrlLoading() to allowlist URLs. Avoid addJavascriptInterface() on API < 17. Consider Chrome Custom Tabs instead.",
                "cwe_id": "CWE-79",
                "cvss_score": 9.3,
            },
            {
                "pattern": r"addJavascriptInterface\s*\(",
                "title": "addJavascriptInterface — JavaScript Bridge Exposes Java API",
                "description": "addJavascriptInterface() exposes annotated Java objects to JavaScript running in the WebView. On Android < 4.2 (API 17), any JavaScript (including injected malicious scripts) can invoke all public methods of the registered object, enabling full RCE.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Ensure @JavascriptInterface annotation is used and minSdkVersion >= 17. Validate all data passed across the bridge. Load only trusted content. Prefer message-passing patterns over direct method exposure.",
                "cwe_id": "CWE-749",
                "cvss_score": 9.8,
            },
            {
                "pattern": r"android:exported\s*=\s*\"true\"",
                "title": "Exported Component Without Permission Check",
                "description": "An Android component (Activity, Service, BroadcastReceiver, or ContentProvider) is exported without declaring a permission requirement. Any app on the device can interact with this component, potentially reading sensitive data or triggering unintended actions.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Add android:permission to the exported component. For ContentProviders, set android:readPermission and android:writePermission. If the component does not need to be public, set android:exported=\"false\".",
                "cwe_id": "CWE-926",
                "cvss_score": 8.1,
            },
            {
                "pattern": r"new\s+X509TrustManager\s*\(\s*\)|checkClientTrusted|checkServerTrusted",
                "title": "Custom TrustManager — SSL Certificate Validation Disabled",
                "description": "A custom X509TrustManager with empty or always-passing checkServerTrusted() bypasses SSL/TLS certificate validation. This allows man-in-the-middle attackers to intercept and modify all HTTPS traffic in cleartext.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Never override certificate validation logic. Use the system default TrustManager. For development, use a network security config with debug overrides. For testing, use a local proxy with a trusted dev certificate.",
                "cwe_id": "CWE-295",
                "cvss_score": 9.0,
            },
            {
                "pattern": r"MODE_WORLD_READABLE|MODE_WORLD_WRITEABLE",
                "title": "World-Readable or World-Writable File Mode",
                "description": "Files created with MODE_WORLD_READABLE or MODE_WORLD_WRITEABLE can be read or written by any app on the device. This exposes sensitive data to untrusted third-party applications.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Use MODE_PRIVATE (the default). Share files with other apps using a FileProvider and content:// URIs with explicit intent permissions.",
                "cwe_id": "CWE-732",
                "cvss_score": 6.5,
            },
            {
                "pattern": r"Runtime\.getRuntime\(\)\.exec\s*\(|ProcessBuilder\s*\(",
                "title": "Command Injection via Runtime.exec()",
                "description": "Executing shell commands via Runtime.exec() or ProcessBuilder with user-controlled input enables command injection. An attacker can append shell metacharacters to run arbitrary commands with the app's permissions.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Avoid shell command execution entirely. If unavoidable, pass arguments as separate array elements to ProcessBuilder (never concatenate into a string). Allowlist and sanitize all input before use.",
                "cwe_id": "CWE-78",
                "cvss_score": 9.8,
            },
            {
                "pattern": r"FLAG_ACTIVITY_NEW_TASK(?!.*FLAG_IMMUTABLE)|PendingIntent\.get(?:Activity|Service|Broadcast)\s*\([^)]*\)",
                "title": "Mutable PendingIntent — Intent Hijacking Risk",
                "description": "PendingIntents created without FLAG_IMMUTABLE (API 31+) or FLAG_UPDATE_CURRENT can be hijacked by malicious apps to modify the Intent's action, data, or extras before it is delivered, potentially escalating privileges.",
                "severity": "Medium",
                "category": "Security",
                "recommendation": "Always specify FLAG_IMMUTABLE when creating PendingIntents unless mutation is explicitly required. Use FLAG_MUTABLE only with inline documentation explaining why.",
                "cwe_id": "CWE-285",
                "cvss_score": 5.9,
            },
            {
                "pattern": r"Cipher\.getInstance\s*\(\s*\"AES\"\s*\)|Cipher\.getInstance\s*\(\s*\"AES/ECB",
                "title": "Insecure AES Mode — ECB or No Mode Specified",
                "description": "Using AES without specifying a mode defaults to ECB (Electronic Codebook) on most Android JCE providers. ECB mode is deterministic and reveals plaintext patterns in ciphertext, making it cryptographically weak and unsuitable for securing data.",
                "severity": "High",
                "category": "Crypto",
                "recommendation": "Use AES/GCM/NoPadding which provides both confidentiality and integrity. Generate a unique IV for each encryption operation. Store IV alongside ciphertext (IV is not secret).",
                "cwe_id": "CWE-327",
                "cvss_score": 7.4,
            },
        ]
