from .base import BaseAnalyzer


class IOSAnalyzer(BaseAnalyzer):
    platform = "ios"

    def rules(self) -> list[dict]:
        return [
            {
                "pattern": r"NSUserDefaults\.standard(?:UserDefaults)?\.set\s*\([^)]*(?:password|token|secret|key|auth)[^)]*\)|UserDefaults\.standard\.set\s*\([^)]*(?:password|token|secret|key)[^)]*\)",
                "title": "Sensitive Data Stored in NSUserDefaults",
                "description": "NSUserDefaults (UserDefaults in Swift) stores data in an unencrypted plist file on the device filesystem. Tokens, passwords, or session identifiers stored here are readable by anyone with filesystem access (jailbroken devices, backup extraction).",
                "severity": "High",
                "category": "Security",
                "recommendation": "Store sensitive values in the iOS Keychain using SecItemAdd/SecItemCopyMatching or a wrapper like KeychainAccess. Use kSecAttrAccessibleWhenUnlockedThisDeviceOnly for maximum protection.",
                "cwe_id": "CWE-312",
                "cvss_score": 7.1,
            },
            {
                "pattern": r"kSecAttrAccessibleAlways(?:ThisDeviceOnly)?(?!\s*//)",
                "title": "Keychain Item Accessible When Device Is Locked",
                "description": "The Keychain accessibility attribute kSecAttrAccessibleAlways or kSecAttrAccessibleAlwaysThisDeviceOnly allows reading the Keychain item even when the device is locked. This weakens the protection against attackers who have physical access to an unlocked device or exploit a vulnerability.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Use kSecAttrAccessibleWhenUnlockedThisDeviceOnly for maximum security. For background-accessible items use kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly and document the reason.",
                "cwe_id": "CWE-522",
                "cvss_score": 6.8,
            },
            {
                "pattern": r"NSLog\s*\(@?\"[^\"]*(?:password|token|secret|key|auth|credential)[^\"]*\"",
                "title": "Sensitive Data Logged via NSLog in Release Build",
                "description": "NSLog output is visible in the device console (accessible via Xcode, Console.app, or idevicesyslog). Logging sensitive data such as passwords, auth tokens, or API keys in production code exposes them to anyone with physical or ADB-equivalent access to the device.",
                "severity": "Medium",
                "category": "Security",
                "recommendation": "Wrap all NSLog calls in #if DEBUG / #endif blocks. In Swift, use os_log with the .private data formatter for sensitive values. Remove or disable verbose logging before releasing to App Store.",
                "cwe_id": "CWE-532",
                "cvss_score": 5.3,
            },
            {
                "pattern": r"NSAllowsArbitraryLoads\s*=\s*(?:YES|true|1)|NSExceptionAllowsInsecureHTTPLoads\s*=\s*(?:YES|true|1)",
                "title": "App Transport Security (ATS) Disabled",
                "description": "Setting NSAllowsArbitraryLoads to YES in Info.plist disables Apple's App Transport Security, allowing cleartext HTTP connections to any server. This exposes all network traffic to man-in-the-middle attacks on insecure networks.",
                "severity": "High",
                "category": "Network",
                "recommendation": "Remove NSAllowsArbitraryLoads. Ensure all server endpoints support HTTPS with TLS 1.2 or higher. If a specific legacy endpoint requires HTTP, use NSExceptionDomains to scope the exception to that domain only.",
                "cwe_id": "CWE-319",
                "cvss_score": 7.4,
            },
            {
                "pattern": r"(?<![a-zA-Z])(\w+)!\.",
                "title": "Force Unwrap of Optional — Crash Risk",
                "description": "Force-unwrapping an Optional with ! will crash the application with a fatal error if the value is nil. Force unwraps in network response handlers, Core Data fetches, or UI code are a common source of production crashes that are difficult to reproduce.",
                "severity": "Medium",
                "category": "Crash",
                "recommendation": "Use guard let, if let, or the nil-coalescing operator (??) to safely unwrap optionals. Use optional chaining (?.) instead of forced member access (!.). If nil is truly impossible, add a fatalError() with an explanatory message.",
                "cwe_id": "CWE-476",
                "cvss_score": 5.0,
            },
            {
                "pattern": r"delegate\s*=\s*self|weak\s+var\s+delegate",
                "title": "Potential Strong Reference Cycle in Delegate Pattern",
                "description": "If a delegate property is declared as strong (the default in Swift) and the delegating object is also retained by the delegate, a retain cycle is created. Both objects are kept alive indefinitely, leaking memory for the lifetime of the app.",
                "severity": "Medium",
                "category": "Memory",
                "recommendation": "Always declare delegate properties as `weak var delegate: SomeProtocol?`. Ensure the delegate protocol is class-bound (`protocol MyDelegate: AnyObject`) so the weak reference is valid.",
                "cwe_id": "CWE-401",
                "cvss_score": 4.3,
            },
            {
                "pattern": r"UIPasteboard\.general\.(string|url|image|items)\s*=",
                "title": "Sensitive Data Written to System Pasteboard",
                "description": "Writing sensitive data to UIPasteboard.general makes it accessible to all apps on the device and, on iOS 16+, is announced to the user with a notification banner. Third-party apps that monitor the pasteboard can silently read credentials placed there.",
                "severity": "Medium",
                "category": "Security",
                "recommendation": "Avoid writing passwords or tokens to the general pasteboard. Use a private named pasteboard (UIPasteboard(name:create:)) for in-app copy operations. For password manager integration, use the AutoFill framework instead.",
                "cwe_id": "CWE-200",
                "cvss_score": 4.3,
            },
            {
                "pattern": r"\.loadHTMLString\s*\(|\.loadRequest\s*\(",
                "title": "WKWebView Loading Potentially Untrusted Content",
                "description": "Loading HTML or URLs from untrusted sources in WKWebView without Content Security Policy (CSP) headers can lead to XSS vulnerabilities. If JavaScript is enabled and the content is user-controlled, attackers may exfiltrate data or call native message handlers.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Set a strict Content Security Policy in your HTML. Validate and sanitize all dynamic HTML content. Disable JavaScript if not needed. Use WKWebView's decidePolicyFor navigationAction to allowlist acceptable URLs.",
                "cwe_id": "CWE-79",
                "cvss_score": 7.5,
            },
            {
                "pattern": r"SecRandomCopyBytes\s*\(|arc4random(?:_uniform)?\s*\(",
                "title": "Verify Cryptographic Randomness Source",
                "description": "arc4random_uniform is suitable for general randomness but verify it is not being used as the sole source of entropy for cryptographic key generation. For security-critical operations, SecRandomCopyBytes with kSecRandomDefault should be used exclusively.",
                "severity": "Low",
                "category": "Crypto",
                "recommendation": "For all cryptographic operations (key generation, nonce, IV, salt), use SecRandomCopyBytes(kSecRandomDefault, count, &buffer). Use arc4random only for non-security-sensitive randomness like UI shuffles.",
                "cwe_id": "CWE-338",
                "cvss_score": 3.7,
            },
            {
                "pattern": r"URLSession\.shared\.dataTask|URLSession\.shared\.downloadTask",
                "title": "Shared URLSession Without Custom Configuration",
                "description": "URLSession.shared uses the default configuration which does not support background transfers, certificate pinning, or custom TLS settings. For sensitive API calls, a dedicated URLSession with a custom URLSessionConfiguration should be used to enforce security policies.",
                "severity": "Low",
                "category": "Network",
                "recommendation": "Create a dedicated URLSession with URLSessionConfiguration.default or .ephemeral. Implement URLSessionDelegate to perform certificate pinning using SecTrustEvaluateWithError. Use background sessions for large transfers.",
                "cwe_id": "CWE-295",
                "cvss_score": 3.1,
            },
        ]
