from .base import BaseAnalyzer


class MacOSAnalyzer(BaseAnalyzer):
    platform = "macos"

    def rules(self) -> list[dict]:
        return [
            {
                "pattern": r"NSTask\s*\(\s*\)|task\.arguments\s*=.*(?:userInput|input|arg|param|value|request)",
                "title": "NSTask with User-Controlled Arguments — Command Injection",
                "description": "Constructing NSTask (Process in Swift) arguments from user-controlled input enables command injection. If the arguments include shell metacharacters and launchPath is set to /bin/sh, attackers can execute arbitrary commands with the app's privileges.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Never pass user-controlled strings directly to NSTask arguments. Use allowlist validation for all inputs. Avoid launchPath = '/bin/sh' with -c; instead pass the command executable directly as launchPath with explicit argument array elements.",
                "cwe_id": "CWE-78",
                "cvss_score": 9.8,
            },
            {
                "pattern": r"kSecAttrAccessibleAlways(?:ThisDeviceOnly)?",
                "title": "Keychain Accessible Always — Weakened Protection",
                "description": "kSecAttrAccessibleAlways or kSecAttrAccessibleAlwaysThisDeviceOnly allows Keychain items to be read even when the device is locked. While less impactful on macOS than iOS (no lock screen), it still violates the principle of least privilege and weakens defense in depth.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Use kSecAttrAccessibleWhenUnlocked for items only needed when the user is active. Use kSecAttrAccessibleAfterFirstUnlock only for daemon/background items that genuinely need access after boot without login. Document the choice.",
                "cwe_id": "CWE-522",
                "cvss_score": 6.8,
            },
            {
                "pattern": r"xpc_connection_create|NSXPCConnection\s*\(|xpc_connection_set_event_handler",
                "title": "XPC Service Without Entitlement Validation",
                "description": "XPC services that do not validate the connecting process's entitlements or code signing identity accept connections from any process on the system. A malicious app can impersonate a trusted caller and invoke privileged XPC methods.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "In the XPC service's connection handler, use SecCodeCopyGuestWithAttributes + SecCodeCheckValidity to verify the caller's code signature. Check com.apple.security.application-groups entitlements. Use NSXPCInterface for type-safe message passing.",
                "cwe_id": "CWE-284",
                "cvss_score": 8.8,
            },
            {
                "pattern": r"NSWorkspace\.shared\.open\s*\(|openURL\s*\(",
                "title": "Unvalidated URL Passed to NSWorkspace.open()",
                "description": "Opening unvalidated URLs with NSWorkspace.shared.open() can trigger malicious URL scheme handlers, cause SSRF, or open dangerous file types. If the URL comes from network responses or user input, attackers can craft URLs that trigger unintended application behavior.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Validate URLs against an allowlist of accepted schemes (https, mailto, etc.). Use URL.scheme to check the protocol. Avoid opening file:// or javascript:// URLs from untrusted sources. Show a confirmation dialog before opening external URLs.",
                "cwe_id": "CWE-601",
                "cvss_score": 7.4,
            },
            {
                "pattern": r"sudo\s+|chmod\s+777\s+|chmod\s+a\+rwx\s+",
                "title": "Overly Permissive Shell Script Permissions",
                "description": "Using sudo without hardened PATH, or setting file permissions to 777/a+rwx, creates privilege escalation and file hijacking opportunities. World-writable files can be modified by any local user to gain elevated privileges or tamper with application data.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Harden sudo usage: set PATH explicitly in scripts before running privileged commands. Never use 777 permissions; use the minimum required (e.g., 644 for data, 755 for executables). Use chmod with symbolic modes and validate files before operating on them.",
                "cwe_id": "CWE-732",
                "cvss_score": 7.8,
            },
            {
                "pattern": r"\.setFileAttributes\s*\(\s*\[\.posixPermissions\s*:\s*0o?777\]|FileManager\.default\.createFile\s*\([^)]*attributes:\s*nil",
                "title": "File Created Without Explicit Permission Attributes",
                "description": "Files created with nil attributes inherit the process's umask, which may be more permissive than intended. On multi-user macOS systems, this can expose sensitive application data to other local users.",
                "severity": "Medium",
                "category": "Security",
                "recommendation": "Always specify explicit POSIX permissions when creating sensitive files: use attributes: [.posixPermissions: 0o600] for user-only read/write. Verify the file was created with the expected permissions after creation.",
                "cwe_id": "CWE-732",
                "cvss_score": 5.5,
            },
            {
                "pattern": r"NSAutoreleasePool\s*\(\s*\)|autoreleasepool\s*\{",
                "title": "Autorelease Pool — Verify Scope for Memory Efficiency",
                "description": "While not a bug by itself, autorelease pools inside tight loops or without being drained frequently can cause significant memory spikes. Objective-C objects added to the pool are not released until the pool drains, potentially causing OOM conditions during batch operations.",
                "severity": "Low",
                "category": "Memory",
                "recommendation": "Wrap the inner body of loops that create many Objective-C objects in @autoreleasepool { ... }. In Swift, use autoreleasepool { } closure for the same effect. Drain pools after processing each batch item.",
                "cwe_id": "CWE-400",
                "cvss_score": 3.7,
            },
            {
                "pattern": r"NSFileManager\.defaultManager\s*\(\s*\)|FileManager\.default",
                "title": "NSFileManager Default Instance Used in Multi-Threaded Context",
                "description": "The NSFileManager default instance is not thread-safe for use on threads other than the main thread. Using it in background queues or DispatchQueue.global() without creating a separate instance per thread can cause race conditions and file system corruption.",
                "severity": "Medium",
                "category": "Performance",
                "recommendation": "Create a new FileManager() instance per thread or dispatch queue: let fm = FileManager(). The default instance is only safe on the main thread. For concurrent file operations, use per-operation FileManager instances.",
                "cwe_id": "CWE-362",
                "cvss_score": 5.9,
            },
            {
                "pattern": r"DispatchQueue\.main\.sync\s*\{",
                "title": "DispatchQueue.main.sync — Potential Deadlock",
                "description": "Calling DispatchQueue.main.sync{} from the main thread causes an immediate deadlock because the main thread is waiting for itself to complete the block. This is a common mistake when refactoring async code and causes the app to freeze completely.",
                "severity": "High",
                "category": "Performance",
                "recommendation": "Never call DispatchQueue.main.sync from the main thread. Use DispatchQueue.main.async for UI updates from background threads. If synchronous main-thread execution is needed from a background thread, document why and use with extreme care.",
                "cwe_id": "CWE-833",
                "cvss_score": 6.5,
            },
            {
                "pattern": r"NSURLConnection\s*\(|NSURLConnection\.sendSynchronousRequest",
                "title": "Deprecated NSURLConnection — Memory and Security Risk",
                "description": "NSURLConnection is deprecated since macOS 10.11 and iOS 9. It has known security limitations (no HTTP/2, limited TLS configuration, no background transfer support) and may not receive security patches. Synchronous variants block the calling thread, causing UI freezes.",
                "severity": "Medium",
                "category": "Network",
                "recommendation": "Migrate to URLSession (NSURLSession). Use URLSession.shared for simple requests or a custom URLSession with URLSessionConfiguration for advanced use cases including certificate pinning, background transfers, and HTTP/2.",
                "cwe_id": "CWE-477",
                "cvss_score": 5.3,
            },
        ]
