from .base import BaseAnalyzer


class WebAnalyzer(BaseAnalyzer):
    platform = "web"

    def rules(self) -> list[dict]:
        return [
            {
                "pattern": r"\"SELECT\s|\"INSERT\s|\"UPDATE\s|\"DELETE\s|\"DROP\s|f\"SELECT|f\"INSERT|f\"UPDATE|f\"DELETE|query\s*\+=\s*|query\s*=\s*\".*\+",
                "title": "SQL Injection — String-Concatenated Query",
                "description": "Constructing SQL queries by concatenating user-supplied strings allows attackers to inject arbitrary SQL. This can bypass authentication, exfiltrate the entire database, modify or delete data, or execute OS commands via database procedures (xp_cmdshell on MSSQL).",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Use parameterized queries / prepared statements exclusively: cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,)). Use an ORM (SQLAlchemy, Django ORM, Hibernate). Validate and sanitize all inputs. Apply principle of least privilege to database users.",
                "cwe_id": "CWE-89",
                "cvss_score": 9.8,
            },
            {
                "pattern": r"innerHTML\s*=|document\.write\s*\(|\.html\s*\([^)]*(?:userInput|input|param|req\.|request\.|data\[)",
                "title": "Cross-Site Scripting (XSS) — Unsanitized HTML Injection",
                "description": "Setting innerHTML or calling document.write() with user-controlled data allows attackers to inject HTML and JavaScript into the page. The injected script runs in the victim's browser session with full access to cookies, localStorage, and DOM, enabling session hijacking and credential theft.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Use textContent instead of innerHTML for text data. Use DOMPurify to sanitize HTML if you must render it. Apply Content Security Policy (CSP) headers. Use framework templating (React JSX, Vue templates) which auto-escape by default.",
                "cwe_id": "CWE-79",
                "cvss_score": 8.8,
            },
            {
                "pattern": r"(?:api[_-]?key|apikey|api[_-]?secret|secret[_-]?key|access[_-]?token|auth[_-]?token|password|passwd|pwd|private[_-]?key)\s*=\s*['\"][A-Za-z0-9+/=_\-]{8,}['\"]",
                "title": "Hardcoded Secret / API Key in Source Code",
                "description": "Hardcoded credentials, API keys, or secrets in source code are exposed to anyone with repository access. If the repository is public or leaked, attackers can immediately use these credentials to access external services, cloud infrastructure, or databases.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Remove all hardcoded secrets immediately. Use environment variables or a secrets manager (AWS Secrets Manager, HashiCorp Vault, Doppler). Rotate any exposed credentials. Add pre-commit hooks (git-secrets, truffleHog) to prevent future occurrences.",
                "cwe_id": "CWE-798",
                "cvss_score": 9.1,
            },
            {
                "pattern": r"\beval\s*\(|\bnew Function\s*\(|\bexec\s*\(|\bexecSync\s*\(",
                "title": "eval() / exec() with Potentially Untrusted Input",
                "description": "Passing user-controlled data to eval(), new Function(), or exec() functions executes it as code in the current context. This enables Remote Code Execution (RCE), allowing attackers to run arbitrary JavaScript/Python on the server or in the victim's browser.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Never use eval() on user input. Replace exec() calls with subprocess.run() using a list of arguments (never shell=True with user input). Use JSON.parse() instead of eval() for parsing. Refactor code to avoid dynamic code evaluation entirely.",
                "cwe_id": "CWE-95",
                "cvss_score": 9.8,
            },
            {
                "pattern": r"hashlib\.md5\s*\(|hashlib\.sha1\s*\(|MD5\s*\(|SHA1\s*\(|CryptoJS\.MD5|bcrypt\.hashSync\s*\([^,]+,\s*[1-5]\s*\)",
                "title": "Weak Cryptographic Hash Algorithm",
                "description": "MD5 and SHA-1 are cryptographically broken and should not be used for password hashing, HMAC, or data integrity verification. MD5 collisions can be generated in seconds. Low bcrypt cost factors (< 10) are vulnerable to brute force on modern hardware.",
                "severity": "High",
                "category": "Crypto",
                "recommendation": "For password hashing: use bcrypt (cost ≥ 12), Argon2id, or scrypt. For data integrity: use SHA-256 or SHA-3. For HMAC: use HMAC-SHA256. Never use MD5 or SHA-1 for security-critical operations.",
                "cwe_id": "CWE-327",
                "cvss_score": 7.5,
            },
            {
                "pattern": r"Access-Control-Allow-Origin:\s*\*|res\.header\s*\(\s*['\"]Access-Control-Allow-Origin['\"],\s*['\"][*]['\"]|app\.use\s*\(\s*cors\s*\(\s*\)\s*\)",
                "title": "Wildcard CORS Policy — Cross-Origin Data Exposure",
                "description": "Setting Access-Control-Allow-Origin: * allows any website to make credentialed cross-origin requests to your API. If authentication uses cookies or HTTP Authorization headers and the CORS policy is too broad, attackers can exfiltrate data from authenticated users via malicious websites.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Set CORS to specific trusted origins: Access-Control-Allow-Origin: https://yourdomain.com. Use an allowlist of trusted origins. Never reflect the Origin header without validation. Combine with Access-Control-Allow-Credentials: false unless needed.",
                "cwe_id": "CWE-942",
                "cvss_score": 7.5,
            },
            {
                "pattern": r"http://(?!localhost|127\.0\.0\.1|0\.0\.0\.0)\w",
                "title": "Insecure HTTP URL in Production Code",
                "description": "Hardcoded http:// URLs for production services transmit data in cleartext. All traffic including authentication tokens, session cookies, and sensitive data is visible to network observers (ISPs, proxies, attackers on the same WiFi network).",
                "severity": "Medium",
                "category": "Network",
                "recommendation": "Use https:// for all production endpoints. Configure HTTP Strict Transport Security (HSTS) headers. Use HTTPS Everywhere or automatic HTTP-to-HTTPS redirects at the reverse proxy level. Store URLs in environment variables to facilitate environment-specific configuration.",
                "cwe_id": "CWE-319",
                "cvss_score": 5.9,
            },
            {
                "pattern": r"open\s*\([^)]*\.\.\./|path\.join\s*\([^)]*(?:req\.|request\.|userInput|input|param)",
                "title": "Path Traversal — Directory Traversal Attack",
                "description": "Constructing file paths from user-supplied input without proper canonicalization allows attackers to use ../ sequences to escape the intended directory and access arbitrary files on the server, including /etc/passwd, SSH keys, or application source code.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Use path.resolve() and verify the result starts with the intended base directory. Use os.path.abspath() and assert it starts with BASE_DIR. Reject any input containing '..' or null bytes. Prefer serving files from a content-addressed store rather than by path.",
                "cwe_id": "CWE-22",
                "cvss_score": 8.6,
            },
            {
                "pattern": r"pickle\.loads\s*\(|pickle\.load\s*\(|yaml\.load\s*\([^)]*(?!Loader=yaml\.SafeLoader|Loader=yaml\.CSafeLoader)",
                "title": "Deserialization of Untrusted Data — RCE Risk",
                "description": "Python's pickle.loads() and PyYAML's yaml.load() (without SafeLoader) execute arbitrary Python code during deserialization. Passing attacker-controlled data to these functions achieves Remote Code Execution with the privileges of the running process.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Never deserialize pickle data from untrusted sources. Use JSON, MessagePack, or Protocol Buffers for data exchange. For YAML, always specify Loader=yaml.SafeLoader or use yaml.safe_load(). Sign serialized data with HMAC if integrity verification is needed.",
                "cwe_id": "CWE-502",
                "cvss_score": 9.8,
            },
            {
                "pattern": r"redirect\s*\(\s*request\.\w+\s*\[|redirect\s*\(\s*req\.query\.|redirect\s*\(\s*req\.params\.",
                "title": "Open Redirect — Unvalidated Redirect Destination",
                "description": "Redirecting users to a URL from request parameters without validation allows attackers to craft phishing URLs that appear legitimate (e.g., yourbank.com/login?next=evil.com). Victims who click such links may be redirected to malicious sites after authentication.",
                "severity": "Medium",
                "category": "Security",
                "recommendation": "Allowlist redirect destinations: only accept relative paths or URLs matching your domain. Use urlparse to extract and validate the host. Reject any redirect destination with a different scheme or host than your application's origin.",
                "cwe_id": "CWE-601",
                "cvss_score": 6.1,
            },
        ]
