from .base import BaseAnalyzer


class WindowsAnalyzer(BaseAnalyzer):
    platform = "windows"

    def rules(self) -> list[dict]:
        return [
            {
                "pattern": r"\bstrcpy\s*\(|\bsprintf\s*\(|\bgets\s*\(|\bstrcat\s*\(",
                "title": "Unsafe C/C++ String Function — Buffer Overflow Risk",
                "description": "Functions like strcpy, sprintf, gets, and strcat do not perform bounds checking. Writing beyond the destination buffer's size overwrites adjacent memory, enabling stack-based buffer overflow attacks. This class of vulnerability has led to countless critical CVEs.",
                "severity": "Critical",
                "category": "Memory",
                "recommendation": "Replace with safe alternatives: strcpy_s, sprintf_s, gets_s, strcat_s (CRT safe functions). Or use std::string in C++. Enable /GS (stack canary), /SAFESEH, and DEP/NX as compiler mitigations.",
                "cwe_id": "CWE-120",
                "cvss_score": 9.8,
            },
            {
                "pattern": r"Process\.Start\s*\(\s*(?:userInput|request|param|arg|value|cmd|command|path)\s*\)|CreateProcess\s*\([^,]+,\s*(?:userInput|cmd|command|arg)",
                "title": "Process Execution with User-Controlled Path — DLL Hijacking",
                "description": "Passing user-controlled strings to Process.Start() or CreateProcess() without validation enables attackers to execute arbitrary programs or load malicious DLLs from attacker-controlled paths. If the executable path includes directories from a writable location, DLL hijacking is possible.",
                "severity": "Critical",
                "category": "Security",
                "recommendation": "Validate and allowlist executable paths. Use absolute paths to executables. Set ProcessStartInfo.UseShellExecute = false. For shell commands, use a hardcoded executable path with separate arguments array.",
                "cwe_id": "CWE-427",
                "cvss_score": 9.3,
            },
            {
                "pattern": r"GC\.SuppressFinalize\s*\(",
                "title": "GC.SuppressFinalize Without Dispose Pattern",
                "description": "Calling GC.SuppressFinalize without implementing IDisposable correctly creates a resource management bug. If the finalizer is suppressed but Dispose() is never called, unmanaged resources (file handles, native memory, COM objects) will leak until GC pressure eventually triggers collection.",
                "severity": "High",
                "category": "Memory",
                "recommendation": "Implement the full IDisposable pattern: public void Dispose() { Dispose(true); GC.SuppressFinalize(this); } protected virtual void Dispose(bool disposing) { ... }. Use the 'using' statement at call sites.",
                "cwe_id": "CWE-401",
                "cvss_score": 6.5,
            },
            {
                "pattern": r"Thread\.Abort\s*\(\s*\)|thread\.Abort\s*\(",
                "title": "Thread.Abort() — Async Cancellation Anti-Pattern",
                "description": "Thread.Abort() throws a ThreadAbortException at an arbitrary point in the thread's execution, potentially in the middle of a finally block or while holding a lock. This can corrupt application state, deadlock, or leave resources unreleased. It is deprecated in .NET 5+.",
                "severity": "High",
                "category": "Performance",
                "recommendation": "Use CancellationToken for cooperative cancellation. Pass a CancellationToken to async operations and check IsCancellationRequested at safe points. For legacy code, use Thread.Interrupt() with a try/catch(ThreadInterruptedException).",
                "cwe_id": "CWE-662",
                "cvss_score": 6.1,
            },
            {
                "pattern": r"RegistryKey\.OpenBaseKey\s*\(.*RegistryHive\.LocalMachine|Registry\.LocalMachine\.OpenSubKey\s*\([^)]*,\s*true\s*\)",
                "title": "Registry HKLM Write Without Elevation Check",
                "description": "Writing to HKEY_LOCAL_MACHINE requires Administrator privileges. Attempting to write without checking for elevated rights will either silently fail (registry virtualization on UAC), throw an UnauthorizedAccessException, or succeed in an unexpected virtualized location, causing subtle bugs.",
                "severity": "High",
                "category": "Security",
                "recommendation": "Check WindowsPrincipal.IsInRole(WindowsBuiltInRole.Administrator) before HKLM writes. Use manifest requiresAdministrator if the app always needs elevation. Prefer per-user HKCU settings to avoid needing elevation entirely.",
                "cwe_id": "CWE-269",
                "cvss_score": 6.5,
            },
            {
                "pattern": r"new\s+SecureString\s*\(\s*\)(?![\s\S]*?\.Dispose\s*\(\s*\))",
                "title": "SecureString Not Disposed — Plaintext Remains in Memory",
                "description": "SecureString stores data in encrypted memory, but if the object is not properly disposed, the unmanaged memory buffer is not zeroed and freed promptly. The sensitive data lingers in memory until GC finalizes the object, increasing the window for memory scraping attacks.",
                "severity": "Medium",
                "category": "Memory",
                "recommendation": "Always use SecureString inside a 'using' block or call .Dispose() in a finally block. Consider that SecureString is deprecated in .NET 6+ — evaluate whether the protection it offers is actually needed in your threat model.",
                "cwe_id": "CWE-316",
                "cvss_score": 5.5,
            },
            {
                "pattern": r"InternetSetOption|INTERNET_OPTION_SECURITY_FLAGS|SECURITY_FLAG_IGNORE_CERT",
                "title": "WinInet SSL Certificate Validation Disabled",
                "description": "Using InternetSetOption with SECURITY_FLAG_IGNORE_CERT_* flags disables SSL certificate validation in WinInet, allowing man-in-the-middle attackers to intercept all HTTPS traffic. This is sometimes used as a 'quick fix' for certificate errors in development but left in production.",
                "severity": "High",
                "category": "Network",
                "recommendation": "Remove all SECURITY_FLAG_IGNORE_CERT_* flags from production code. Fix the underlying certificate issue. Use INTERNET_OPTION_CLIENT_CERT_CONTEXT to present client certificates if required. For testing, use a proper dev certificate.",
                "cwe_id": "CWE-295",
                "cvss_score": 8.1,
            },
            {
                "pattern": r"Marshal\.AllocHGlobal\s*\(|Marshal\.AllocCoTaskMem\s*\(",
                "title": "Unmanaged Memory Allocation — Potential Memory Leak",
                "description": "Marshal.AllocHGlobal and AllocCoTaskMem allocate unmanaged memory that is not tracked by the .NET GC. If a corresponding FreeHGlobal/FreeCoTaskMem call is missing (e.g., due to an exception), the memory leaks for the lifetime of the process.",
                "severity": "High",
                "category": "Memory",
                "recommendation": "Always free unmanaged allocations in a finally block: Marshal.FreeHGlobal(ptr) / Marshal.FreeCoTaskMem(ptr). Consider wrapping in a SafeHandle subclass for automatic release. Use Span<T> or stackalloc for small short-lived buffers instead.",
                "cwe_id": "CWE-401",
                "cvss_score": 6.5,
            },
            {
                "pattern": r"catch\s*\(\s*Exception\s+\w+\s*\)\s*\{[^}]*\}|catch\s*\(\s*\)\s*\{",
                "title": "Swallowed Exception — Silent Error Hiding",
                "description": "Catching all exceptions and doing nothing (empty catch block) or only logging suppresses errors silently. This masks bugs, causes state corruption to go undetected, and makes debugging extremely difficult in production.",
                "severity": "Medium",
                "category": "Logic",
                "recommendation": "Catch only specific, expected exception types. Re-throw unexpected exceptions using 'throw;' (not 'throw ex;' which resets the stack trace). Log all caught exceptions with full stack trace. Consider a global unhandled exception handler.",
                "cwe_id": "CWE-390",
                "cvss_score": 5.3,
            },
            {
                "pattern": r"\bP\/Invoke\b|DllImport\s*\(",
                "title": "P/Invoke Native Interop — Manual Memory Safety Required",
                "description": "P/Invoke calls into native DLLs bypass .NET's type safety and memory management. Incorrect marshaling (wrong calling convention, mismatched types, missing SafeHandle) causes stack corruption, access violations, or memory leaks that are difficult to debug.",
                "severity": "Medium",
                "category": "Memory",
                "recommendation": "Use SafeHandle or CriticalHandle for native handles. Validate all DllImport signatures against the C header. Use [MarshalAs] attributes explicitly. Prefer LibraryImport (source-gen P/Invoke) in .NET 7+ for better performance and safety. Document the calling convention.",
                "cwe_id": "CWE-119",
                "cvss_score": 5.9,
            },
        ]
